apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "atala-prism-dev-deployments-github-docker-registry-key"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: {{ .Values.secrets.secretStore | quote }}
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .dockerconfigjson | b64dec }}` }}"
  dataFrom:
    - extract:
        key: {{ .Values.secrets.dockerRegistryToken | quote }}

---

{{- $root := . -}}
{{- range $consumer := .Values.ingress.auth.externalConsumers }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ $root.Values.ingress.auth.externalConsumerKeyPrefix }}-{{ $consumer | lower }}"
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "labels.common" $root | nindent 4 }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: {{ $root.Values.secrets.secretStore | quote }}
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "{{ $root.Values.ingress.auth.externalConsumerKeyPrefix }}-{{ $consumer | lower }}"
---
{{- end }}
