{{- if .Values.ingress.enabled }}
{{- $root := . -}}
{{- range $consumer := .Values.ingress.auth.consumers }}
apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: StringSecret
metadata:
  name: "{{ $root.Release.Namespace }}-{{ $consumer | lower }}"
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "labels.common" $root | nindent 4 }}
spec:
  forceRegenerate: false
  data:
    username: {{ $consumer | lower }}
  fields:
    - fieldName: "key"
      encoding: "base64"
      length: "32"
---
{{- end }}
{{- end }}
