apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: StringSecret
metadata:
  name: "agent-keycloak-client-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  forceRegenerate: false
  fields:
    - fieldName: "secret"
      encoding: "base64"
      length: "16"

---

apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: StringSecret
metadata:
  name: "keycloak-admin-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  forceRegenerate: false
  fields:
    - fieldName: "password"
      encoding: "base64"
      length: "32"
    - fieldName: "postgres-password"
      encoding: "base64"
      length: "32"
