{{- if .Values.server.useVault }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-unseal-cronjob
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: vault-unseal-cronjob
        spec:
          restartPolicy: OnFailure
          containers:
            - name: vault-unseal-cronjob
              image: "ghcr.io/omegion/vault-unseal:v0.9.0"
              imagePullPolicy: IfNotPresent
              env:
                - name: VAULT_UNSEAL_KEY_0
                  valueFrom:
                    secretKeyRef:
                      name: vault-unseal-key-0
                      key: unseal-key
                - name: VAULT_UNSEAL_KEY_1
                  valueFrom:
                    secretKeyRef:
                      name: vault-unseal-key-1
                      key: unseal-key
                - name: VAULT_UNSEAL_KEY_2
                  valueFrom:
                    secretKeyRef:
                      name: vault-unseal-key-2
                      key: unseal-key
              args:
                - unseal
                - --address=http://{{ .Release.Namespace }}-vault.{{ .Release.Namespace }}:8200
                - --shard=$(VAULT_UNSEAL_KEY_0)
                - --shard=$(VAULT_UNSEAL_KEY_1)
                - --shard=$(VAULT_UNSEAL_KEY_2)
{{- end }}
