---
version: "3.8"

services:
  ##########################
  # Services
  ##########################

  prism-node:
    image: ghcr.io/input-output-hk/prism-node:${PRISM_NODE_VERSION}
    environment:
      NODE_REFRESH_AND_SUBMIT_PERIOD:
      NODE_MOVE_SCHEDULED_TO_PENDING_PERIOD:
      NODE_WALLET_MAX_TPS:
      NODE_LEDGER: ${NODE_LEDGER}
      NODE_PSQL_HOST: ${PGHOST}:${PGPORT:-5432}
      NODE_PSQL_DATABASE: ${NODE_PGDATABASE:-node}
      NODE_PSQL_USERNAME: ${PGUSER}
      NODE_PSQL_PASSWORD: ${PGPASSWORD}
      NODE_NETWORK: ${NODE_NETWORK:-mainnet}
      NODE_CARDANO_WALLET_ID: ${WALLET_ID}
      NODE_CARDANO_NETWORK: ${CARDANO_NETWORK:-mainnet}
      NODE_CARDANO_PAYMENT_ADDRESS: ${WALLET_PAYMENT_ADDRESS}
      NODE_CARDANO_WALLET_PASSPHRASE: ${WALLET_PASSPHRASE}
      NODE_CARDANO_WALLET_API_HOST: ${WALLET_HOST}
      NODE_CARDANO_WALLET_API_PORT: ${WALLET_PORT}
      NODE_CARDANO_WALLET_ROUTING_HEADER_NAME: ${WALLET_ROUTING_HEADER}
      NODE_CARDANO_DB_SYNC_HOST: ${PGHOST}:${PGPORT:-5432}
      NODE_CARDANO_DB_SYNC_DATABASE: ${CARDANO_PGDATABASE:-cardano}
      NODE_CARDANO_DB_SYNC_USERNAME: ${PGUSER}
      NODE_CARDANO_DB_SYNC_PASSWORD: ${PGPASSWORD}
      NODE_CARDANO_CONFIRMATION_BLOCKS: ${CONFIRMATION_BLOCKS:-25}

  vault-server:
    image: hashicorp/vault:latest
    ports:
      - "127.0.0.1:8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
    command: server
    volumes:
    - ${VAULT_CONFIG_PATH:-./vault.hcl}:/vault/config/config.hcl:ro
    - /opt/vault:/vault/data
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  cloud-agent:
    image: ghcr.io/hyperledger/identus-cloud-agent:${AGENT_VERSION}
    environment:
      POLLUX_DB_HOST: ${PGHOST}
      POLLUX_DB_PORT: ${PGPORT:-5432}
      POLLUX_DB_NAME: ${POLLUX_PGDBDATABASE:-pollux}
      POLLUX_DB_USER: ${PGUSER}
      POLLUX_DB_PASSWORD: ${PGPASSWORD}
      CONNECT_DB_HOST: ${PGHOST}
      CONNECT_DB_PORT: ${PGPORT:-5432}
      CONNECT_DB_NAME: ${CONNECT_PGDBDATABASE:-connect}
      CONNECT_DB_USER: ${PGUSER}
      CONNECT_DB_PASSWORD: ${PGPASSWORD}
      AGENT_DB_HOST: ${PGHOST}
      AGENT_DB_PORT: ${PGPORT:-5432}
      AGENT_DB_NAME: ${AGENT_PGDBDATABASE:-agent}
      AGENT_DB_USER: ${PGUSER}
      AGENT_DB_PASSWORD: ${PGPASSWORD}
      POLLUX_STATUS_LIST_REGISTRY_PUBLIC_URL: https://agent.socious.io/cloud-agent
      DIDCOMM_SERVICE_URL: https://agent.socious.io/didcomm
      REST_SERVICE_URL: https://agent.socious.io/cloud-agent
      PRISM_NODE_HOST: prism-node
      PRISM_NODE_PORT: 50053
      VAULT_ADDR: ${VAULT_ADDR:-http://vault-server:8200}
      VAULT_TOKEN: ${VAULT_TOKEN:-root}
      SECRET_STORAGE_BACKEND: ${SECRET_STORAGE_BACKEND:-vault}
      VAULT_USE_SEMANTIC_PATH: 'false'
      DEFAULT_WALLET_ENABLED:
      DEFAULT_WALLET_SEED:
      DEFAULT_WALLET_WEBHOOK_URL:
      DEFAULT_WALLET_WEBHOOK_API_KEY:
      DEFAULT_WALLET_AUTH_API_KEY:
      GLOBAL_WEBHOOK_URL:
      GLOBAL_WEBHOOK_API_KEY:
      WEBHOOK_PARALLELISM:
      ADMIN_TOKEN:
      API_KEY_SALT: ${AGENT_APIKEY}
      API_KEY_ENABLED: ${AGENT_APIKEY_ENABLED:-false}
      API_KEY_AUTHENTICATE_AS_DEFAULT_USER:
      API_KEY_AUTO_PROVISIONING:
    depends_on:
      prism-node:
        condition: service_started
      vault-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cloud-agent:8085/_system/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.1.0
    environment:
      - 'URLS=[
        { name: "Cloud Agent", url: "/docs/cloud-agent/api/docs.yaml" }
        ]'

  apisix:
    image: apache/apisix:2.15.0-alpine
    volumes:
      - ./apisix/conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
      - ./apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "${PORT}:9080/tcp"
    depends_on:
      - cloud-agent
      - swagger-ui